name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily at midnight
  workflow_dispatch: # Allows you to run it manually
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jenil1236
          template: classic
          base: header, repositories
          config_timezone: Asia/Kolkata
          
          # Languages Plugin
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # Calendar Plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Achievements Plugin
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
